### ISSUE TITLE
Mangaku

### ISSUE THREAD

**Issue by owengofficial** [KotatsuApp/kotatsu-parsers#383] opened 2023-11-16 18:36 UTC
### Source name

mangaku

### Source link

https://mangaku.team/

### Language

indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2023-11-16 20:49
Duplicate of #360, again. Bumping request will not make adding a source any faster, be patient.

**Closed by ztimms73** 2023-11-16 20:49 UTC
Labels: source request
