### ISSUE TITLE
Manhwas.net

### ISSUE THREAD

**Issue by isaacpsx** [KotatsuApp/kotatsu-parsers#459] opened 2024-01-11 19:09 UTC
### Source name

Manhwas.net

### Source link

https://manhwas.net/

### Language

spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-02-03 10:08
Duplicate of #344

**Closed by davvarrr** 2024-02-03 10:08 UTC
Labels: source request

**Comment by isaacpsx** [comment] 2024-02-03 13:56
Sorry about that i Hope that my other sources are compatibles
