### ISSUE TITLE
Readcomiconline source request!

### ISSUE THREAD

**Issue by Pempo01** [KotatsuApp/kotatsu-parsers#874] opened 2024-07-01 00:11 UTC
### Source name

Readcomiconline

### Source link

https://readcomiconline.li/

### Language

English

### Other details

I know its not necessarily manga. With other extension-based readers being down, Kotatsu has become my number 1 option. Problem is Xoxxo and Comic extra have a ton of problems and the quality is really poor. Please consider my suggestion. Thank you so much.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by Pempo01** [comment] 2024-07-03 14:04
Note that this is a COMPLETELY DIFFERENT source than readcomicsonline.ru. That source is already in the app and, in fact, has great quality comics, but lacks the diversity the source I suggested has.

**Comment by davvarrr** [comment] 2024-07-06 16:53
Duplicate of [#671](https://github.com/KotatsuApp/kotatsu-parsers/issues/671)

**Closed by davvarrr** 2024-07-06 16:53 UTC
Labels: source request
