### ISSUE TITLE
source requests please! 18+

### ISSUE THREAD

**Issue by kolinrno** [KotatsuApp/kotatsu-parsers#149] opened 2023-02-09 18:36 UTC
### Source name

read details

### Source link

read_details.co

### Language

INDONESIA

### Other details

Android 5.0
 Request Source;
 Doujin desu = doujindesu.xxx
Komikcast = Komikcast.me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by kolinrno** [comment] 2023-02-09 18:39
thank you, it would be nice to focus on open sources first

**Comment by Koitharu** [comment] 2023-06-02 07:54
The url [read_details.co](http://read_details.co) is not accessible for me, is it alive?

**Comment by ztimms73** [comment] 2023-06-02 08:06
DoujinDesu now available, komikcast - duplicate of #79

**Closed** 2023-06-02 08:06 UTC
Labels: source request
