### ISSUE TITLE
WickedWitchScan not working

### ISSUE THREAD

**Issue by Josue18js** [KotatsuApp/kotatsu-parsers#788] opened 2024-05-26 17:06 UTC
### Source information

WickedWitchScan 

### Steps to reproduce

WickedWitchScan  source isn't working.

### Kotatsu version

7.1.1

### Android version

Android 13

### Other details

WickedWitchScan  source isn't working.
When I click the source it said "failed to connect to wickedwitchscan.com"
![Screenshot_20240526_135759_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/92787197/61f2949f-fe24-4f19-805a-e3831485f19e)
![Screenshot_20240526_140519_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/92787197/a7554ba3-9594-44e6-af4a-4b3c17bf2fcb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment] 2024-07-06 17:34
Duplicate of https://github.com/KotatsuApp/kotatsu-parsers/issues/571

**Closed by davvarrr** 2024-07-06 17:34 UTC
Labels: bug
