### ISSUE TITLE
Por favor añadan Ikigai Mangas 🙏

### ISSUE THREAD

**Issue by 1222Kan** [KotatsuApp/kotatsu-parsers#735] opened 2024-05-08 18:43 UTC
### Source name

IkigaiMangas

### Source link

https://visorikigai.net/

### Language

Español

### Other details

Hace unas semanas mencionaron que se debía eliminar la fuente yugen 😓puesto que no funciona y hicieron una solicitud para agregar Ikigai Mangas, va hace un tiempo que está así y nada 🙏por favor

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2024-05-08 22:02
Duplicate of #716

**Closed by ztimms73** 2024-05-08 22:02 UTC
Labels: source request
