### ISSUE TITLE
TyrantScans português 

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#410] opened 2023-12-14 11:22 UTC
### Source name

TyrantScans

### Source link

https://www.tyrantscans.com/

### Language

português 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2023-12-14 11:34
Duplicate of #363

**Closed by davvarrr** 2023-12-14 11:34 UTC
Labels: source request
