### ISSUE TITLE
Add MangaReader.to in source 

### ISSUE THREAD

**Issue by neop6969** [KotatsuApp/kotatsu-parsers#487] opened 2024-01-15 17:55 UTC
### Source name

MangaReader 

### Source link

https://mangareader.to/

### Language

English 

### Other details

It's one of the best manga reading website with one of the best collection of mangas and they are updated on regular basis 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2024-01-15 19:45
Duplicate of #234

**Closed** 2024-01-15 19:46 UTC
Labels: source request
