### ISSUE TITLE
mangaku

### ISSUE THREAD

**Issue by owengofficial** [KotatsuApp/kotatsu-parsers#414] opened 2023-12-16 10:40 UTC
### Source name

mangaku

### Source link

https://mangaku.mom/

### Language

Indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2023-12-16 10:56
If you really want this source, you only have to contribute instead of bringing it up again and again. I don't even want to see it added, this behavior is so annoying.

**Comment by davvarrr** [comment] 2023-12-16 13:35
duplicate of #360

**Closed by davvarrr** 2023-12-16 13:35 UTC
Labels: duplicate, source request
