### ISSUE TITLE
Omega scans isn't working 

### ISSUE THREAD

**Issue by Akira1309** [KotatsuApp/kotatsu-parsers#654] opened 2024-03-22 17:53 UTC
### Source information

Omega scans

### Kotatsu version

6.8

### Android version

14

### Other details

![Screenshot_2024-03-22-23-22-14-35_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/kotatsu-parsers/assets/91799799/955dc8fe-db97-42db-8d51-5cc7a4967a3d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment] 2024-03-22 19:12
duplicate of #641

**Closed** 2024-07-06 17:40 UTC
Labels: bug
