### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by KENN1408** [KotatsuApp/kotatsu-parsers#549] opened 2024-02-05 23:46 UTC
### Source information

YugenMangas.lat

### Steps to reproduce

1. Open YuguenManga 
2. select any story

### Kotatsu version

6.6.8

### Android version

12

### Other details

There is a source that changed its domain, since it did not update it automatically I changed it manually to ikigaimangas.com since it is the domain they use now, but now it opens the page with its updates but when I press it in a story the following appears

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment] 2024-07-06 17:20
Duplicate of #538

**Closed by davvarrr** 2024-07-06 17:20 UTC
Labels: bug
