### ISSUE TITLE
slimeread (nsfw) - Portugues

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#476] opened 2024-01-12 13:59 UTC
### Source name

slimeread (nsfw)

### Source link

https://slimeread.com/nsfw

### Language

português 

### Other details

and another site, which has the +18 version (NSFW)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-02-03 10:06
Duplicate of #326

**Closed by davvarrr** 2024-02-03 10:06 UTC
Labels: source request
