### ISSUE TITLE
[Source request] KomikIndo

### ISSUE THREAD

**Issue by alpqm** [KotatsuApp/kotatsu-parsers#111] opened 2022-11-12 03:04 UTC
### Source name

komikIndoID

### Source link

https://komikindo.id/

### Language

Indonesian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2022-11-20 11:13
Duplicate of #80

**Closed** 2022-11-20 11:13 UTC
Labels: source request
