### ISSUE TITLE
Some Arabic Websites #1

### ISSUE THREAD

**Issue by Amirbrnjallon** [KotatsuApp/kotatsu-parsers#726] opened 2024-05-02 18:56 UTC
### Source name

Dilar

### Source link

https://dilar.tube/

### Language

Arabic

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-07-06 17:07
Duplicate of https://github.com/KotatsuApp/kotatsu-parsers/issues/304

**Closed by davvarrr** 2024-07-06 17:07 UTC
Labels: source request

**Comment by OtakuArab** [comment] 2024-07-06 19:35
> Duplicate of #304

and you 
https://www.mangatales.com/
