### ISSUE TITLE
Add Mangago in English as a source

### ISSUE THREAD

**Issue by M0M03** [KotatsuApp/kotatsu-parsers#774] opened 2024-05-22 20:38 UTC
### Source name

Mangago

### Source link

https://mangago.me/

### Language

English 

### Other details

I've searched everywhere and I believe this source hasn't been suggested or added yet.
I don't know how possible it'd be to add it but I thank you nevertheless.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-07-06 16:11
Duplicate of #205

**Closed by davvarrr** 2024-07-06 16:11 UTC
Labels: source request
