### ISSUE TITLE
Manhwas.net source

### ISSUE THREAD

**Issue by Paquitowebeo** [KotatsuApp/kotatsu-parsers#822] opened 2024-06-02 01:11 UTC
### Source name

Manhwas.net

### Source link

https://manhwas.net

### Language

Spanish

### Other details

This source is very popular in latinamerica 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-06-22 16:27
Duplicate of https://github.com/KotatsuApp/kotatsu-parsers/issues/344

**Closed by davvarrr** 2024-06-22 16:27 UTC
Labels: source request
