### ISSUE TITLE
Add to source Tsuki Mangás

### ISSUE THREAD

**Issue by DollynDeveloper** [KotatsuApp/kotatsu-parsers#758] opened 2024-05-13 16:10 UTC
### Source name

Tsuki Mangás 

### Source link

https://tsuki-mangas.com/

### Language

Portuguese Brazil

### Other details

This is a site that provides manga for the Brazilian language, there is no need for big steps for reading, just access the site. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by EvaldoCeBr** [comment] 2024-05-13 17:26
The source has already been requested in another thread!

**Comment by davvarrr** [comment] 2024-07-06 16:01
Duplicate of #320

**Closed by davvarrr** 2024-07-06 16:01 UTC
Labels: source request
