### ISSUE TITLE
Mangaku

### ISSUE THREAD

**Issue by owengofficial** [KotatsuApp/kotatsu-parsers#369] opened 2023-11-10 14:56 UTC
### Source name

mangaku

### Source link

https://mangaku.blog/

### Language

Indonesia

### Other details

please consider this source, other sources from Indonesia only take manga updates from the mangaku site. please reconsider. embarrassing
I waited a long time for this source to be included.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2023-11-11 08:10
Duplicate of #360

**Closed** 2023-11-11 08:10 UTC
Labels: source request
