### ISSUE TITLE
[Shinigami] Doesn't work

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/kotatsu-parsers#334] opened 2023-10-26 03:55 UTC
### Source information

Shinigami

### Steps to reproduce

1. Explore -> Shinigami
2. Nothing show
![Screenshot_2023-10-26-10-53-19-126_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/9708ee64-93fb-43ed-984a-a1a1da2ed471)
3. Web version
![Screenshot_2023-10-26-10-53-55-282_com opera browser](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/ffa91022-04ae-4d17-9f56-caec104b23f1)

### Kotatsu version

6.2.3 

### Android version

Android 12

### Other details

Note :
I updated the link from 'shinigami.ae' to 'shinigami.sh'.
But still don't work
![Screenshot_2023-10-26-10-55-36-081_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/03ac6a28-dbc8-4f18-96c6-c3bea44ed9e9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment] 2023-10-26 06:06
Duplicate of #319

**Closed by davvarrr** 2023-10-26 06:06 UTC
Labels: bug

**Comment by MIRVOUS** [comment] 2023-10-26 06:21
Sorry
