### ISSUE TITLE
G Manga

### ISSUE THREAD

**Issue by blackcatad** [KotatsuApp/kotatsu-parsers#376] opened 2023-11-12 19:55 UTC
### Source name

G Manga

### Source link

https://gmanga.org/

### Language

arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2023-11-12 20:16
Duplicate of #247

**Closed by davvarrr** 2023-11-12 20:16 UTC
Labels: source request
