### ISSUE TITLE
the extension is not working

### ISSUE THREAD

**Issue by Chellyph14** [KotatsuApp/kotatsu-parsers#675] opened 2024-04-03 14:14 UTC
### Source information

WickedWitchScan

### Steps to reproduce

Every time I open it, it says there was an error, try again.
Her domain is okay, it's just not working.

### Kotatsu version

6.8.3

### Android version

Android 11

### Other details

![Screenshot_20240403-101253_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/111191378/a91f6fed-6d7d-4950-82b5-2b1a5e832458)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by nomaxsnx** [comment] 2024-04-04 14:41
even changing the site's domain, because the old site was "madara", now it's "peach".

**Comment by davvarrr** [comment] 2024-07-06 17:34
Duplicate of https://github.com/KotatsuApp/kotatsu-parsers/issues/571

**Closed by davvarrr** 2024-07-06 17:34 UTC
Labels: bug
