### ISSUE TITLE
Omegascans is not working

### ISSUE THREAD

**Issue by BigBagelBoss** [KotatsuApp/kotatsu-parsers#653] opened 2024-03-22 16:31 UTC
### Source information

OmegaScans

### Steps to reproduce

1. Opening the source will give the errors, making me unable to view anything:
Cannot find script.ContainsData(Genres)
Cannot find script.ContainsData(chapter_slug)
![IMG_20240322_181627](https://github.com/KotatsuApp/kotatsu-parsers/assets/164536888/e06c0233-438a-43e5-8653-96e904f8dbaf)
![IMG_20240322_181613](https://github.com/KotatsuApp/kotatsu-parsers/assets/164536888/ed7b0eb7-b849-4650-8a04-5293b8a1d92b)
 

### Kotatsu version

6.8

### Android version

Android 13

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment] 2024-03-22 17:30
duplicate of #641

**Closed** 2024-03-23 22:17 UTC
Labels: bug
