### ISSUE TITLE
Mangago

### ISSUE THREAD

**Issue by Delmarcop52** [KotatsuApp/kotatsu-parsers#488] opened 2024-01-15 19:58 UTC
### Source name

Mangago

### Source link

https://www.mangago.me

### Language

English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-02-03 10:05
Duplicate of #205

**Closed by davvarrr** 2024-02-03 10:05 UTC
Labels: source request

**Comment by lilmushoo** [comment] 2024-03-21 14:41
Source doesn't show up for me

**Comment by mai2367** [comment] 2024-04-16 04:31
can't find the source!
