### ISSUE TITLE
FlixScans : Error in the thread

### ISSUE THREAD

**Issue by OtakuArab** [KotatsuApp/kotatsu-parsers#596] opened 2024-02-28 15:39 UTC
### Source information

FlixScan

### Steps to reproduce

Access to the source
Network error
Note that the browser works without any problems, the link

### Kotatsu version

6.7.4

### Android version

Android 12

### Other details

![Screenshot_٢٠٢٤٠٢٢٨-١٨٣٦٤٤_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/161339329/b0459e6e-4b59-465c-a5f5-4d8caf2bd794)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment] 2024-07-06 15:59
Duplicate of #547

**Closed by davvarrr** 2024-07-06 15:59 UTC
Labels: bug
