### ISSUE TITLE
source: mangaworldadult

### ISSUE THREAD

**Issue by MegaGamer39** [KotatsuApp/kotatsu-parsers#500] opened 2024-01-17 19:40 UTC
### Source name

mangaworldadult

### Source link

https://www.mangaworldadult.net/

### Language

Italian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2024-01-17 19:55
Duplicate of #465

**Closed** 2024-01-17 19:55 UTC
Labels: source request
