### ISSUE TITLE
MangaWorld

### ISSUE THREAD

**Issue by alan-ford** [KotatsuApp/kotatsu-parsers#464] opened 2024-01-12 10:35 UTC
### Source name

MangaWorld

### Source link

https://www.mangaworld.bz/

### Language

Italian

### Other details

18+/ NO

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2024-01-17 19:53
Duplicate of #438

**Closed** 2024-01-17 19:53 UTC
Labels: source request
