### ISSUE TITLE
Mangá livre

### ISSUE THREAD

**Issue by epsilons9** [KotatsuApp/kotatsu-parsers#305] opened 2023-10-14 01:24 UTC
### Source name

Mangá livre

### Source link

https://mangalivre.net/

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2023-10-14 05:35
Duplicate of #92

**Closed by davvarrr** 2023-10-14 05:35 UTC
Labels: source request
