### ISSUE TITLE
Solicitud de fuente Mangas.in

### ISSUE THREAD

**Issue by 1222Kan** [KotatsuApp/kotatsu-parsers#750] opened 2024-05-11 17:20 UTC
### Source name

Mangas.in

### Source link

https://mangas.in/

### Language

Español 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment] 2024-07-06 17:04
Duplicate of [#455](https://github.com/KotatsuApp/kotatsu-parsers/issues/455)

**Closed by davvarrr** 2024-07-06 17:04 UTC
Labels: source request
