### ISSUE TITLE
Mangaku

### ISSUE THREAD

**Issue by owengofficial** [KotatsuApp/kotatsu-parsers#377] opened 2023-11-13 10:43 UTC
### Source name

Mangaku

### Source link

https://mangaku.blog/

### Language

Indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment] 2023-11-13 11:33
Duplicate of #360

**Closed** 2023-11-13 11:33 UTC
Labels: source request

**Comment by owengofficial** [comment] 2023-11-13 13:11
why my request has no planned ? is that something weird?

**Comment by owengofficial** [comment] 2023-11-13 13:12
i see many source request has done, and mine rejected

**Comment by owengofficial** [comment] 2023-11-13 13:17
f**k this sh*t

**Comment by davvarrr** [comment] 2023-11-13 13:17
@owengofficial You had yourself closed the #360 exit and you opened another one, then for the same source if it's to bring it back up you shouldn't do that, leave the #360 open but don't add other exits for the same.source.
